### ISSUE TITLE
Clarify the spec version to be adopted from WebVR CG

### ISSUE THREAD

**Issue by anssiko** [w3c/webvr-charter#1]
The WG charter draft states in its [Deliverables][1] section:

>The Working Group will deliver the following W3C normative specifications:
>
>WebVR API [...] [Adopted from WebVR CG][2]

The charter should clarify the version of the WebVR API spec to be adopted.

Assuming "[v2.0][3]" will be adopted by the WG, and [v1.1][4] maintenance will continue in the CG in parallel.

Seeking feedback from @cvan @toji.

[1]: https://w3c.github.io/webvr-charter/vr-wg-charter.html#deliverables
[2]: https://w3c.github.io/webvr/
[3]: https://w3c.github.io/webvr/spec/latest/
[4]: https://w3c.github.io/webvr/spec/1.1/

**Comment by toji** [comment]
Correct. The version numbers are for discussion within the group only, and we do not intend them to be reflected externally. Once complete 2.0 will completely replace 1.1, and will simply be known as the WebVR spec.
